apiVersion: v1
kind: Secret
metadata:
  name: simplephone
  namespace: production
type: Opaque
data:
  username: admin
  password: db_password
  port: 3306
  db_endpoint: terraform-20220804102512706800000001.ctojmmaa9cxq.us-east-1.rds.amazonaws.com