---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: Secret
metadata:
  name: simplephone
  namespace: production
type: Opaque
data:
  username: YWRtaW4=
  password: db_password
  db_endpoint: db-endpoint
  api_secret_key: api-secret-key
