---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: Secret
metadata:
  name: simplephone
  namespace: production
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: db_password
  DB_HOSTNAME: db-endpoint
  API_SECRET_KEY: api-secret-key
